package com.nickmcummins.webscraping.org.eclipsecolorthemes.converter;

import com.nickmcummins.webscraping.SchemeType;
import com.nickmcummins.webscraping.converter.ThemeConverter;
import com.nickmcummins.webscraping.org.eclipsecolorthemes.EclipseColorTheme;
import com.nickmcummins.webscraping.visualstudiocode.VSCodeColor;
import com.nickmcummins.webscraping.visualstudiocode.VisualStudioCodeTheme;

import java.util.List;
import java.util.Map;

import static com.nickmcummins.webscraping.SchemeType.DARK;
import static com.nickmcummins.webscraping.SchemeType.LIGHT;
import static com.nickmcummins.webscraping.visualstudiocode.VSCodeColorSetting.*;

public class EclipseToVSCodeThemeConverter implements ThemeConverter<EclipseColorTheme, VisualStudioCodeTheme> {
    private static final Map<SchemeType, List<VSCodeColor>> VSCODE_COLOR_DEFAULTS = Map.of(
            LIGHT, List.of(
                    new VSCodeColor(FOCUS_BORDER, "00000000"),
                    new VSCodeColor(FOREGROUND, "393a34"),
                    new VSCodeColor(DESCRIPTION_FOREGROUND, "393a3490"),
                    new VSCodeColor(ERROR_FOREGROUND, "ab5959"),
                    new VSCodeColor(TEXT_LINK_FOREGROUND, "1c6b48"),
                    new VSCodeColor(TEXT_LINK_ACTIVE_FOREGROUND, "1c6b48"),
                    new VSCodeColor(TEXT_BLOCK_QUOTE_BACKGROUND, "ffffff"),
                    new VSCodeColor(TEXT_BLOCK_QUOTE_BORDER, "f0f0f0"),
                    new VSCodeColor(TEXT_CODE_BLOCK_BACKGROUND, "ffffff"),
                    new VSCodeColor(TEXT_PREFORMAT_FOREGROUND, "586069"),
                    new VSCodeColor(TEXT_SEPARATOR_FOREGROUND, "d1d5da"),
                    new VSCodeColor(BUTTON_BACKGROUND, "1c6b48"),
                    new VSCodeColor(BUTTON_FOREGROUND, "ffffff"),
                    new VSCodeColor(BUTTON_HOVER_BACKGROUND, "1c6b48"),
                    new VSCodeColor(CHECKBOX_BACKGROUND, "f5f5f5"),
                    new VSCodeColor(CHECKBOX_BORDER, "d1d5da"),
                    new VSCodeColor(DROPDOWN_BACKGROUND, "ffffff"),
                    new VSCodeColor(DROPDOWN_BORDER, "f0f0f0"),
                    new VSCodeColor(DROPDOWN_FOREGROUND, "393a34"),
                    new VSCodeColor(DROPDOWN_LIST_BACKGROUND, "f5f5f5"),
                    new VSCodeColor(INPUT_BACKGROUND, "f5f5f5"),
                    new VSCodeColor(INPUT_BORDER, "f0f0f0"),
                    new VSCodeColor(INPUT_FOREGROUND, "393a34"),
                    new VSCodeColor(INPUT_PLACEHOLDER_FOREGROUND, "393a3490"),
                    new VSCodeColor(BADGE_FOREGROUND, "ffffff"),
                    new VSCodeColor(BADGE_BACKGROUND, "393a3490"),
                    new VSCodeColor(PROGRESS_BAR_BACKGROUND, "1c6b48"),
                    new VSCodeColor(TITLE_BAR_ACTIVE_FOREGROUND, "4e4f47"),
                    new VSCodeColor(TITLE_BAR_ACTIVE_BACKGROUND, "ffffff"),
                    new VSCodeColor(TITLE_BAR_INACTIVE_FOREGROUND, "6a737d"),
                    new VSCodeColor(TITLE_BAR_INACTIVE_BACKGROUND, "ffffff"),
                    new VSCodeColor(TITLE_BAR_BORDER, "f5f5f5"),
                    new VSCodeColor(ACTIVITY_BAR_FOREGROUND, "393a34"),
                    new VSCodeColor(ACTIVITY_BAR_INACTIVE_FOREGROUND, "393a3450"),
                    new VSCodeColor(ACTIVITY_BAR_BACKGROUND, "ffffff"),
                    new VSCodeColor(ACTIVITY_BAR_BADGE_FOREGROUND, "ffffff"),
                    new VSCodeColor(ACTIVITY_BAR_BADGE_BACKGROUND, "4e4f47"),
                    new VSCodeColor(ACTIVITY_BAR_ACTIVE_BORDER, "1c6b48"),
                    new VSCodeColor(ACTIVITY_BAR_BORDER, "f0f0f0"),
                    new VSCodeColor(SIDE_BAR_FOREGROUND, "4e4f47"),
                    new VSCodeColor(SIDE_BAR_BACKGROUND, "ffffff"),
                    new VSCodeColor(SIDE_BAR_BORDER, "f0f0f0"),
                    new VSCodeColor(SIDE_BAR_TITLE_FOREGROUND, "393a34"),
                    new VSCodeColor(SIDE_BAR_SECTION_HEADER_FOREGROUND, "393a34"),
                    new VSCodeColor(SIDE_BAR_SECTION_HEADER_BACKGROUND, "ffffff"),
                    new VSCodeColor(SIDE_BAR_SECTION_HEADER_BORDER, "f0f0f0"),
                    new VSCodeColor(LIST_HOVER_FOREGROUND, "393a34"),
                    new VSCodeColor(LIST_INACTIVE_SELECTION_FOREGROUND, "393a34"),
                    new VSCodeColor(LIST_ACTIVE_SELECTION_FOREGROUND, "393a34"),
                    new VSCodeColor(LIST_HOVER_BACKGROUND, "f5f5f5"),
                    new VSCodeColor(LIST_INACTIVE_SELECTION_BACKGROUND, "ffffff"),
                    new VSCodeColor(LIST_ACTIVE_SELECTION_BACKGROUND, "f5f5f5"),
                    new VSCodeColor(LIST_INACTIVE_FOCUS_BACKGROUND, "ffffff"),
                    new VSCodeColor(LIST_FOCUS_BACKGROUND, "f5f5f5"),
                    new VSCodeColor(TREE_INDENT_GUIDES_STROKE, "e1e4e8"),
                    new VSCodeColor(NOTIFICATION_CENTER_HEADER_FOREGROUND, "6a737d"),
                    new VSCodeColor(NOTIFICATION_CENTER_HEADER_BACKGROUND, "ffffff"),
                    new VSCodeColor(NOTIFICATIONS_FOREGROUND, "393a34"),
                    new VSCodeColor(NOTIFICATIONS_BACKGROUND, "ffffff"),
                    new VSCodeColor(NOTIFICATIONS_BORDER, "f0f0f0"),
                    new VSCodeColor(NOTIFICATIONS_ERROR_ICON_FOREGROUND, "ab5959"),
                    new VSCodeColor(NOTIFICATIONS_WARNING_ICON_FOREGROUND, "a65e2b"),
                    new VSCodeColor(NOTIFICATIONS_INFO_ICON_FOREGROUND, "296aa3"),
                    new VSCodeColor(PICKER_GROUP_BORDER, "e1e4e8"),
                    new VSCodeColor(PICKER_GROUP_FOREGROUND, "393a34"),
                    new VSCodeColor(QUICK_INPUT_BACKGROUND, "ffffff"),
                    new VSCodeColor(QUICK_INPUT_FOREGROUND, "393a34"),
                    new VSCodeColor(STATUS_BAR_FOREGROUND, "4e4f47"),
                    new VSCodeColor(STATUS_BAR_BACKGROUND, "ffffff"),
                    new VSCodeColor(STATUS_BAR_BORDER, "f0f0f0"),
                    new VSCodeColor(STATUS_BAR_NO_FOLDER_BACKGROUND, "ffffff"),
                    new VSCodeColor(STATUS_BAR_DEBUGGING_BACKGROUND, "f5f5f5"),
                    new VSCodeColor(STATUS_BAR_DEBUGGING_FOREGROUND, "4e4f47"),
                    new VSCodeColor(STATUS_BAR_ITEM_PROMINENT_BACKGROUND, "f5f5f5"),
                    new VSCodeColor(EDITOR_GROUP_HEADER_TABS_BACKGROUND, "ffffff"),
                    new VSCodeColor(EDITOR_GROUP_HEADER_TABS_BORDER, "f0f0f0"),
                    new VSCodeColor(EDITOR_GROUP_BORDER, "f0f0f0"),
                    new VSCodeColor(TAB_ACTIVE_FOREGROUND, "393a34"),
                    new VSCodeColor(TAB_INACTIVE_FOREGROUND, "6a737d"),
                    new VSCodeColor(TAB_INACTIVE_BACKGROUND, "ffffff"),
                    new VSCodeColor(TAB_ACTIVE_BACKGROUND, "ffffff"),
                    new VSCodeColor(TAB_HOVER_BACKGROUND, "f5f5f5"),
                    new VSCodeColor(TAB_UNFOCUSED_HOVER_BACKGROUND, "ffffff"),
                    new VSCodeColor(TAB_BORDER, "f0f0f0"),
                    new VSCodeColor(TAB_UNFOCUSED_ACTIVE_BORDER_TOP, "f0f0f0"),
                    new VSCodeColor(TAB_ACTIVE_BORDER, "f0f0f0"),
                    new VSCodeColor(TAB_UNFOCUSED_ACTIVE_BORDER, "f0f0f0"),
                    new VSCodeColor(TAB_ACTIVE_BORDER_TOP, "ffffff"),
                    new VSCodeColor(BREADCRUMB_FOREGROUND, "6a737d"),
                    new VSCodeColor(BREADCRUMB_FOCUS_FOREGROUND, "393a34"),
                    new VSCodeColor(BREADCRUMB_ACTIVE_SELECTION_FOREGROUND, "586069"),
                    new VSCodeColor(BREADCRUMB_PICKER_BACKGROUND, "ffffff"),
                    new VSCodeColor(EDITOR_FOREGROUND, "393a34"),
                    new VSCodeColor(EDITOR_BACKGROUND, "ffffff"),
                    new VSCodeColor(EDITOR_WIDGET_BACKGROUND, "ffffff"),
                    new VSCodeColor(EDITOR_FOLD_BACKGROUND, "ffffff"),
                    new VSCodeColor(EDITOR_LINE_HIGHLIGHT_BACKGROUND, "f5f5f5"),
                    new VSCodeColor(EDITOR_LINE_NUMBER_FOREGROUND, "393a3450"),
                    new VSCodeColor(EDITOR_LINE_NUMBER_ACTIVE_FOREGROUND, "4e4f47"),
                    new VSCodeColor(EDITOR_INDENT_GUIDE_BACKGROUND, "eff2f6"),
                    new VSCodeColor(EDITOR_INDENT_GUIDE_ACTIVE_BACKGROUND, "d7dbe0"),
                    new VSCodeColor(EDITOR_WHITESPACE_FOREGROUND, "d1d5da"),
                    new VSCodeColor(EDITOR_FIND_MATCH_BACKGROUND, "e6cc7744"),
                    new VSCodeColor(EDITOR_FIND_MATCH_HIGHLIGHT_BACKGROUND, "e6cc7766"),
                    new VSCodeColor(EDITOR_INACTIVE_SELECTION_BACKGROUND, "0366d611"),
                    new VSCodeColor(EDITOR_SELECTION_BACKGROUND, "1c6b4820"),
                    new VSCodeColor(EDITOR_SELECTION_HIGHLIGHT_BACKGROUND, "1c6b4830"),
                    new VSCodeColor(EDITOR_WORD_HIGHLIGHT_BACKGROUND, "1c6b4805"),
                    new VSCodeColor(EDITOR_WORD_HIGHLIGHT_STRONG_BACKGROUND, "1c6b4810"),
                    new VSCodeColor(EDITOR_BRACKET_MATCH_BACKGROUND, "1c6b4820"),
                    new VSCodeColor(DIFF_EDITOR_INSERTED_TEXT_BACKGROUND, "1c6b4822"),
                    new VSCodeColor(DIFF_EDITOR_REMOVED_TEXT_BACKGROUND, "ab595920"),
                    new VSCodeColor(SCROLLBAR_SHADOW, "6a737d33"),
                    new VSCodeColor(SCROLLBAR_SLIDER_BACKGROUND, "393a3410"),
                    new VSCodeColor(SCROLLBAR_SLIDER_HOVER_BACKGROUND, "393a3450"),
                    new VSCodeColor(SCROLLBAR_SLIDER_ACTIVE_BACKGROUND, "393a3450"),
                    new VSCodeColor(EDITOR_OVERVIEW_RULER_BORDER, "fff"),
                    new VSCodeColor(PANEL_BACKGROUND, "ffffff"),
                    new VSCodeColor(PANEL_BORDER, "f0f0f0"),
                    new VSCodeColor(PANEL_TITLE_ACTIVE_BORDER, "1c6b48"),
                    new VSCodeColor(PANEL_TITLE_ACTIVE_FOREGROUND, "393a34"),
                    new VSCodeColor(PANEL_TITLE_INACTIVE_FOREGROUND, "6a737d"),
                    new VSCodeColor(PANEL_INPUT_BORDER, "e1e4e8"),
                    new VSCodeColor(TERMINAL_FOREGROUND, "393a34"),
                    new VSCodeColor(TERMINAL_ANSI_BRIGHT_BLACK, "121212"),
                    new VSCodeColor(TERMINAL_ANSI_BRIGHT_BLUE, "296aa3"),
                    new VSCodeColor(TERMINAL_ANSI_BRIGHT_CYAN, "2993a3"),
                    new VSCodeColor(TERMINAL_ANSI_BRIGHT_GREEN, "1c6b48"),
                    new VSCodeColor(TERMINAL_ANSI_BRIGHT_MAGENTA, "b05a78"),
                    new VSCodeColor(TERMINAL_ANSI_BRIGHT_RED, "ab5959"),
                    new VSCodeColor(TERMINAL_ANSI_BRIGHT_WHITE, "dbd7ca"),
                    new VSCodeColor(TERMINAL_ANSI_BRIGHT_YELLOW, "bda437"),
                    new VSCodeColor(TERMINAL_ANSI_BLACK, "121212"),
                    new VSCodeColor(TERMINAL_ANSI_BLUE, "296aa3"),
                    new VSCodeColor(TERMINAL_ANSI_CYAN, "2993a3"),
                    new VSCodeColor(TERMINAL_ANSI_GREEN, "1c6b48"),
                    new VSCodeColor(TERMINAL_ANSI_MAGENTA, "b05a78"),
                    new VSCodeColor(TERMINAL_ANSI_RED, "ab5959"),
                    new VSCodeColor(TERMINAL_ANSI_WHITE, "dbd7ca"),
                    new VSCodeColor(TERMINAL_ANSI_YELLOW, "bda437"),
                    new VSCodeColor(GIT_DECORATION_ADDED_RESOURCE_FOREGROUND, "1c6b48"),
                    new VSCodeColor(GIT_DECORATION_MODIFIED_RESOURCE_FOREGROUND, "296aa3"),
                    new VSCodeColor(GIT_DECORATION_DELETED_RESOURCE_FOREGROUND, "ab5959"),
                    new VSCodeColor(GIT_DECORATION_UNTRACKED_RESOURCE_FOREGROUND, "2993a3"),
                    new VSCodeColor(GIT_DECORATION_IGNORED_RESOURCE_FOREGROUND, "393a3450"),
                    new VSCodeColor(GIT_DECORATION_CONFLICTING_RESOURCE_FOREGROUND, "a65e2b"),
                    new VSCodeColor(GIT_DECORATION_SUBMODULE_RESOURCE_FOREGROUND, "393a3490"),
                    new VSCodeColor(EDITOR_GUTTER_MODIFIED_BACKGROUND, "296aa3"),
                    new VSCodeColor(EDITOR_GUTTER_ADDED_BACKGROUND, "1c6b48"),
                    new VSCodeColor(EDITOR_GUTTER_DELETED_BACKGROUND, "ab5959"),
                    new VSCodeColor(DEBUG_TOOL_BAR_BACKGROUND, "ffffff"),
                    new VSCodeColor(EDITOR_STACK_FRAME_HIGHLIGHT_BACKGROUND, "fffbdd"),
                    new VSCodeColor(EDITOR_FOCUSED_STACK_FRAME_HIGHLIGHT_BACKGROUND, "fff5b1"),
                    new VSCodeColor(PEEK_VIEW_EDITOR_BACKGROUND, "ffffff"),
                    new VSCodeColor(PEEK_VIEW_RESULT_BACKGROUND, "ffffff"),
                    new VSCodeColor(SETTINGS_HEADER_FOREGROUND, "393a34"),
                    new VSCodeColor(SETTINGS_MODIFIED_ITEM_INDICATOR, "1c6b48"),
                    new VSCodeColor(WELCOME_PAGE_BUTTON_BACKGROUND, "f6f8fa"),
                    new VSCodeColor(WELCOME_PAGE_BUTTON_HOVER_BACKGROUND, "e1e4e8"),
                    new VSCodeColor(PROBLEMS_ERROR_ICON_FOREGROUND, "ab5959"),
                    new VSCodeColor(PROBLEMS_WARNING_ICON_FOREGROUND, "a65e2b"),
                    new VSCodeColor(PROBLEMS_INFO_ICON_FOREGROUND, "296aa3"),
                    new VSCodeColor(EDITOR_ERROR_FOREGROUND, "ab5959"),
                    new VSCodeColor(EDITOR_WARNING_FOREGROUND, "a65e2b"),
                    new VSCodeColor(EDITOR_INFO_FOREGROUND, "296aa3"),
                    new VSCodeColor(EDITOR_HINT_FOREGROUND, "1c6b48"),
                    new VSCodeColor(EDITOR_GUTTER_COMMENT_RANGE_FOREGROUND, "393a3450"),
                    new VSCodeColor(EDITOR_GUTTER_FOLDING_CONTROL_FOREGROUND, "393a3490")
            ),
            DARK, List.of()
    );
    @Override
    public VisualStudioCodeTheme convert(EclipseColorTheme inputTheme) {
        return null;
    }
}
